### ISSUE TITLE
[python3.5] TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by bittracker** [jansegre/dhcplib#2]
Hi Thanks for your awsome work!

Unfortunately I've found a bug on python3.5, may someone like to fix it? If not please see this Report just as documentation!

Thanks again!
bittracker

### Bug Report: 
```bash
python --version
Python 3.5.3
```
https://github.com/jansegre/dhcplib/blob/9e97d9077ae5cddceada25260f86f3b0cf53fa99/dhcplib/conversion.py#L165-L174

raises the following:
```
./venv/lib/python3.5/site-packages/dhcplib/conversion.py", line 174, in <listcomp>
    return [ord(c) for c in s.encode('utf-8')]
TypeError: ord() expected string of length 1, but int found
```

I think removing the `encode('utf-8')` will fix this error (Python3 strings are "always" utf8)

**Comment by jansegre** [comment]
I see, actually it's better to remove the `ord` call. Otherwise `ord(c)` could yield values higher than 256, because iterating over a Python 3 str, means iterating over unicode code points. On the other hand, encoding a str into bytes (by using an specific encoding, like utf-8) makes it possible to iterate over individual bytes (rather than code points) which are always less than 256.

I'll push a fix soon, this error may be present on other places and was almost certainly introduced when I was converting the original Python 2 code to Python 3.

**Comment by bittracker** [comment]
Thanks for your future Investigation! I'm looking forward to your changes and would be pleased to test them.

**Comment by jansegre** [comment]
I've found no other similar case. New version up on pypi already (0.1.1). Thanks for finding and reporting the bug!
